import { Topic } from "./types/gamesiinterface";

export const instruments = () => {
  const mydata = [
    {
      id: 0,
      val: "Select Instrument",
      name: "Select Instrument",
    },
    {
      id: 1,
      val: "Piano",
      name: "piano",
    },
    {
      id: 2,
      val: "Guitar",
      name: "guitar",
    },
    {
      id: 3,
      val: "Bass",
      name: "bass",
    },
    {
      id: 4,
      val: "Saxophone",
      name: "saxophone",
    },
    {
      id: 5,
      val: "Trumpet",
      name: "trumpet",
    },
    {
      id: 6,
      val: "Trombone",
      name: "trombone",
    },
    {
      id: 7,
      val: "Drums",
      name: "drums",
    },
    {
      id: 8,
      val: "Ukulele",
      name: "ukulele",
    },
    {
      id: 9,
      val: "Violin",
      name: "violin",
    },
    {
      id: 10,
      val: "Cello",
      name: "cello",
    },
    {
      id: 11,
      val: "Vocalist",
      name: "vocalist",
    },
  ];
  return mydata;
};

export const experiences = () => {
  const mydata = [
    {
      id: 0,
      val: "Choose Experience",
      name: "Choose Experience",
    },
    {
      id: 1,
      val: "No Experience",
      name: "noexp",
    },
    {
      id: 2,
      val: "1yrs",
      name: "one-year",
    },
    {
      id: 3,
      val: "2-5yrs",
      name: "two-to-five-years",
    },
    {
      id: 4,
      val: "5-10yrs",
      name: "five-to-10 yrs",
    },
    {
      id: 5,
      val: "more than 10",
      name: "more-than-10yrs",
    },
  ];
  return mydata;
};

export const days = () => {
  const mydata = [
    {
      id: 0 + "noday",
      val: "",
      name: "No Day",
    },
    {
      id: 0,
      val: "Monday",
      name: "Monday",
    },
    {
      id: 1,
      val: "Tuesday",
      name: "Tuesday",
    },
    {
      id: 2,
      val: "wednesday",
      name: "Wednesday",
    },
    {
      id: 3,
      val: "Thursday",
      name: "Thursday",
    },
    {
      id: 4,
      val: "Friday",
      name: "Friday",
    },
    {
      id: 5,
      val: "Saturday",
      name: "Saturday",
    },
    {
      id: 6,
      val: "Sunday",
      name: "Sunday",
    },
  ];
  return mydata;
};

export const topics: Topic[] = [
  {
    name: "Geography",
    description: "Test your knowledge of world geography",
    icon: "\ud83c\udf0d",
    questions: [
      {
        question: "Where is Kenya located?",
        correctAnswer: "Africa",
        otherGuesses: ["South America", "Europe", "Asia"],
        timeLimit: 15,
      },
      {
        question: "Which country has the largest population?",
        correctAnswer: "China",
        otherGuesses: ["India", "USA", "Indonesia"],
        timeLimit: 15,
      },
      {
        question: "Which river is the longest in the world?",
        correctAnswer: "Nile",
        otherGuesses: ["Amazon", "Yangtze", "Mississippi"],
        timeLimit: 15,
      },
      {
        question: "What is the capital of Canada?",
        correctAnswer: "Ottawa",
        otherGuesses: ["Toronto", "Vancouver", "Montreal"],
        timeLimit: 15,
      },
      {
        question: "Which desert is the largest in the world?",
        correctAnswer: "Sahara",
        otherGuesses: ["Gobi", "Arabian", "Kalahari"],
        timeLimit: 15,
      },
      {
        question: "Mount Everest is located in which mountain range?",
        correctAnswer: "Himalayas",
        otherGuesses: ["Andes", "Rockies", "Alps"],
        timeLimit: 15,
      },
      {
        question: "Which country is shaped like a boot?",
        correctAnswer: "Italy",
        otherGuesses: ["Brazil", "Greece", "Thailand"],
        timeLimit: 10,
      },
      {
        question: "What is the smallest country in the world?",
        correctAnswer: "Vatican City",
        otherGuesses: ["Monaco", "San Marino", "Liechtenstein"],
        timeLimit: 15,
      },
      {
        question: "Which continent contains the most freshwater lakes?",
        correctAnswer: "North America",
        otherGuesses: ["Asia", "Africa", "Europe"],
        timeLimit: 15,
      },
      {
        question: "What percentage of Earth's surface is covered by water?",
        correctAnswer: "71%",
        otherGuesses: ["50%", "60%", "80%"],
        timeLimit: 15,
      },
      {
        question: "Which country has the most time zones?",
        correctAnswer: "France",
        otherGuesses: ["Russia", "USA", "China"],
        timeLimit: 15,
      },
      {
        question: "What is the capital of Australia?",
        correctAnswer: "Canberra",
        otherGuesses: ["Sydney", "Melbourne", "Perth"],
        timeLimit: 15,
      },
      {
        question: "Which U.S. state is the largest by area?",
        correctAnswer: "Alaska",
        otherGuesses: ["Texas", "California", "Montana"],
        timeLimit: 15,
      },
      {
        question: "Which sea is the saltiest?",
        correctAnswer: "Dead Sea",
        otherGuesses: ["Red Sea", "Mediterranean Sea", "Black Sea"],
        timeLimit: 15,
      },
      {
        question: "Which country is both in Europe and Asia?",
        correctAnswer: "Turkey",
        otherGuesses: ["Egypt", "Greece", "Russia"],
        timeLimit: 15,
      },
      {
        question: "What is the deepest ocean trench?",
        correctAnswer: "Mariana Trench",
        otherGuesses: ["Puerto Rico Trench", "Java Trench", "Tonga Trench"],
        timeLimit: 15,
      },
      {
        question: "Which African country was never colonized?",
        correctAnswer: "Ethiopia",
        otherGuesses: ["Nigeria", "South Africa", "Kenya"],
        timeLimit: 15,
      },
      {
        question: "What is the flattest continent?",
        correctAnswer: "Australia",
        otherGuesses: ["Antarctica", "Africa", "South America"],
        timeLimit: 15,
      },
      {
        question: "Which country has the most islands?",
        correctAnswer: "Sweden",
        otherGuesses: ["Canada", "Indonesia", "Philippines"],
        timeLimit: 15,
      },
      {
        question: "What is the most widely spoken language in the world?",
        correctAnswer: "Mandarin Chinese",
        otherGuesses: ["English", "Spanish", "Hindi"],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "History",
    description: "Journey through historical events",
    icon: "\ud83c\udfdb\ufe0f",
    questions: [
      {
        question: "In which year did World War II end?",
        correctAnswer: "1945",
        otherGuesses: ["1939", "1941", "1950"],
        timeLimit: 20,
      },
      {
        question: "Who was the first president of the United States?",
        correctAnswer: "George Washington",
        otherGuesses: ["Thomas Jefferson", "Abraham Lincoln", "John Adams"],
        timeLimit: 20,
      },
      {
        question: "What wall fell in 1989?",
        correctAnswer: "Berlin Wall",
        otherGuesses: ["Great Wall of China", "Hadrian's Wall", "Western Wall"],
        timeLimit: 20,
      },
      {
        question: "Who invented the telephone?",
        correctAnswer: "Alexander Graham Bell",
        otherGuesses: ["Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"],
        timeLimit: 20,
      },
      {
        question: "Which ancient civilization built the pyramids?",
        correctAnswer: "Egyptians",
        otherGuesses: ["Mayans", "Aztecs", "Romans"],
        timeLimit: 15,
      },
      {
        question: "When did the Titanic sink?",
        correctAnswer: "1912",
        otherGuesses: ["1905", "1918", "1923"],
        timeLimit: 15,
      },
      {
        question: "Who was the first woman to fly solo across the Atlantic?",
        correctAnswer: "Amelia Earhart",
        otherGuesses: [
          "Bessie Coleman",
          "Harriet Quimby",
          "Jacqueline Cochran",
        ],
        timeLimit: 20,
      },
      {
        question: "Which empire was ruled by Genghis Khan?",
        correctAnswer: "Mongol Empire",
        otherGuesses: ["Ottoman Empire", "Roman Empire", "British Empire"],
        timeLimit: 15,
      },
      {
        question: "In what year did the American Revolution begin?",
        correctAnswer: "1775",
        otherGuesses: ["1776", "1789", "1765"],
        timeLimit: 20,
      },
      {
        question: "Who painted the Mona Lisa?",
        correctAnswer: "Leonardo da Vinci",
        otherGuesses: ["Michelangelo", "Raphael", "Donatello"],
        timeLimit: 15,
      },
      {
        question: "What was the name of the first successful vaccine?",
        correctAnswer: "Smallpox vaccine",
        otherGuesses: [
          "Polio vaccine",
          "Measles vaccine",
          "Tuberculosis vaccine",
        ],
        timeLimit: 20,
      },
      {
        question: "Which ancient wonder was located in Babylon?",
        correctAnswer: "Hanging Gardens",
        otherGuesses: [
          "Great Pyramid",
          "Colossus of Rhodes",
          "Lighthouse of Alexandria",
        ],
        timeLimit: 20,
      },
      {
        question: "Who discovered penicillin?",
        correctAnswer: "Alexander Fleming",
        otherGuesses: ["Louis Pasteur", "Marie Curie", "Jonas Salk"],
        timeLimit: 15,
      },
      {
        question: "What was the main writing system of ancient Egypt?",
        correctAnswer: "Hieroglyphics",
        otherGuesses: ["Cuneiform", "Alphabet", "Sanskrit"],
        timeLimit: 15,
      },
      {
        question:
          "Which war was fought between the North and South in the U.S.?",
        correctAnswer: "Civil War",
        otherGuesses: [
          "Revolutionary War",
          "War of 1812",
          "Mexican-American War",
        ],
        timeLimit: 15,
      },
      {
        question: "Who was the first emperor of Rome?",
        correctAnswer: "Augustus",
        otherGuesses: ["Julius Caesar", "Nero", "Constantine"],
        timeLimit: 20,
      },
      {
        question: "What year did the French Revolution begin?",
        correctAnswer: "1789",
        otherGuesses: ["1776", "1799", "1812"],
        timeLimit: 20,
      },
      {
        question: "Which civilization invented paper?",
        correctAnswer: "Chinese",
        otherGuesses: ["Egyptian", "Greek", "Mesopotamian"],
        timeLimit: 15,
      },
      {
        question: "Who wrote the Declaration of Independence?",
        correctAnswer: "Thomas Jefferson",
        otherGuesses: ["George Washington", "Benjamin Franklin", "John Adams"],
        timeLimit: 15,
      },
      {
        question: "What was the first permanent English settlement in America?",
        correctAnswer: "Jamestown",
        otherGuesses: ["Plymouth", "Roanoke", "Boston"],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "Science",
    description: "Explore the wonders of science",
    icon: "\ud83d\udd2c",
    questions: [
      {
        question: "What planet is known as the Red Planet?",
        correctAnswer: "Mars",
        otherGuesses: ["Jupiter", "Venus", "Saturn"],
        timeLimit: 15,
      },
      {
        question: "What gas do plants absorb from the atmosphere?",
        correctAnswer: "Carbon Dioxide",
        otherGuesses: ["Oxygen", "Nitrogen", "Hydrogen"],
        timeLimit: 15,
      },
      {
        question: "What is the hardest natural substance on Earth?",
        correctAnswer: "Diamond",
        otherGuesses: ["Quartz", "Topaz", "Ruby"],
        timeLimit: 15,
      },
      {
        question: "How many bones are in the adult human body?",
        correctAnswer: "206",
        otherGuesses: ["200", "212", "198"],
        timeLimit: 15,
      },
      {
        question: "What is the chemical symbol for gold?",
        correctAnswer: "Au",
        otherGuesses: ["Ag", "Go", "Gd"],
        timeLimit: 10,
      },
      {
        question: "What is the speed of light?",
        correctAnswer: "299,792 km/s",
        otherGuesses: ["150,000 km/s", "450,000 km/s", "100,000 km/s"],
        timeLimit: 20,
      },
      {
        question: "Which blood type is the universal donor?",
        correctAnswer: "O negative",
        otherGuesses: ["A positive", "B negative", "AB positive"],
        timeLimit: 15,
      },
      {
        question: "What is the largest organ in the human body?",
        correctAnswer: "Skin",
        otherGuesses: ["Liver", "Brain", "Lungs"],
        timeLimit: 15,
      },
      {
        question: "What force keeps planets in orbit around the sun?",
        correctAnswer: "Gravity",
        otherGuesses: ["Magnetism", "Friction", "Inertia"],
        timeLimit: 15,
      },
      {
        question: "What is the main component of the sun?",
        correctAnswer: "Hydrogen",
        otherGuesses: ["Helium", "Oxygen", "Carbon"],
        timeLimit: 15,
      },
      {
        question: "Which planet has the most moons?",
        correctAnswer: "Jupiter",
        otherGuesses: ["Saturn", "Neptune", "Uranus"],
        timeLimit: 15,
      },
      {
        question: "What is the study of fossils called?",
        correctAnswer: "Paleontology",
        otherGuesses: ["Archaeology", "Geology", "Anthropology"],
        timeLimit: 15,
      },
      {
        question: "Which element has the atomic number 1?",
        correctAnswer: "Hydrogen",
        otherGuesses: ["Oxygen", "Carbon", "Helium"],
        timeLimit: 10,
      },
      {
        question: "What is the pH value of pure water?",
        correctAnswer: "7",
        otherGuesses: ["5", "8", "10"],
        timeLimit: 10,
      },
      {
        question: "Which scientist developed the theory of relativity?",
        correctAnswer: "Albert Einstein",
        otherGuesses: ["Isaac Newton", "Galileo Galilei", "Stephen Hawking"],
        timeLimit: 15,
      },
      {
        question: "What is the largest planet in our solar system?",
        correctAnswer: "Jupiter",
        otherGuesses: ["Saturn", "Neptune", "Earth"],
        timeLimit: 10,
      },
      {
        question: "What is the chemical formula for table salt?",
        correctAnswer: "NaCl",
        otherGuesses: ["H2O", "CO2", "CaCO3"],
        timeLimit: 15,
      },
      {
        question: "Which gas is most abundant in Earth's atmosphere?",
        correctAnswer: "Nitrogen",
        otherGuesses: ["Oxygen", "Carbon dioxide", "Argon"],
        timeLimit: 15,
      },
      {
        question: "What is the unit of electrical resistance?",
        correctAnswer: "Ohm",
        otherGuesses: ["Volt", "Ampere", "Watt"],
        timeLimit: 15,
      },
      {
        question: "Which part of the plant conducts photosynthesis?",
        correctAnswer: "Leaf",
        otherGuesses: ["Root", "Stem", "Flower"],
        timeLimit: 10,
      },
    ],
  },
  {
    name: "Movies",
    description: "Test your film knowledge",
    icon: "\ud83c\udfac",
    questions: [
      {
        question: "Which movie won Best Picture at the 2020 Oscars?",
        correctAnswer: "Parasite",
        otherGuesses: ["1917", "Joker", "Once Upon a Time in Hollywood"],
        timeLimit: 20,
      },
      {
        question: "Who directed 'Inception'?",
        correctAnswer: "Christopher Nolan",
        otherGuesses: [
          "Steven Spielberg",
          "James Cameron",
          "Quentin Tarantino",
        ],
        timeLimit: 15,
      },
      {
        question: "Which actor played Jack in Titanic?",
        correctAnswer: "Leonardo DiCaprio",
        otherGuesses: ["Brad Pitt", "Tom Cruise", "Johnny Depp"],
        timeLimit: 15,
      },
      {
        question: "What is the highest-grossing film of all time?",
        correctAnswer: "Avatar",
        otherGuesses: [
          "Avengers: Endgame",
          "Titanic",
          "Star Wars: The Force Awakens",
        ],
        timeLimit: 15,
      },
      {
        question: "Which movie features the song 'Let It Go'?",
        correctAnswer: "Frozen",
        otherGuesses: ["Moana", "Tangled", "The Little Mermaid"],
        timeLimit: 10,
      },
      {
        question: "Who played the Joker in The Dark Knight?",
        correctAnswer: "Heath Ledger",
        otherGuesses: ["Joaquin Phoenix", "Jack Nicholson", "Jared Leto"],
        timeLimit: 15,
      },
      {
        question: "Which movie is about a clownfish searching for his son?",
        correctAnswer: "Finding Nemo",
        otherGuesses: ["Shark Tale", "The Little Mermaid", "A Bug's Life"],
        timeLimit: 10,
      },
      {
        question: "What is the name of the hobbit played by Elijah Wood?",
        correctAnswer: "Frodo Baggins",
        otherGuesses: ["Bilbo Baggins", "Samwise Gamgee", "Peregrin Took"],
        timeLimit: 15,
      },
      {
        question:
          "Which movie features the quote 'You can't handle the truth!'?",
        correctAnswer: "A Few Good Men",
        otherGuesses: [
          "The Shawshank Redemption",
          "Good Will Hunting",
          "Scent of a Woman",
        ],
        timeLimit: 20,
      },
      {
        question: "What year was the first Star Wars movie released?",
        correctAnswer: "1977",
        otherGuesses: ["1980", "1975", "1983"],
        timeLimit: 20,
      },
      {
        question: "Which actress played Katniss in The Hunger Games?",
        correctAnswer: "Jennifer Lawrence",
        otherGuesses: ["Emma Watson", "Kristen Stewart", "Shailene Woodley"],
        timeLimit: 15,
      },
      {
        question: "What is the name of the wizard school in Harry Potter?",
        correctAnswer: "Hogwarts",
        otherGuesses: ["Beauxbatons", "Durmstrang", "Ilvermorny"],
        timeLimit: 10,
      },
      {
        question: "Which movie features a house made of balloons?",
        correctAnswer: "Up",
        otherGuesses: ["Inside Out", "Coco", "Wall-E"],
        timeLimit: 10,
      },
      {
        question: "Who directed Pulp Fiction?",
        correctAnswer: "Quentin Tarantino",
        otherGuesses: ["Martin Scorsese", "Guy Ritchie", "David Fincher"],
        timeLimit: 15,
      },
      {
        question: "Which movie features the character Tony Stark?",
        correctAnswer: "Iron Man",
        otherGuesses: ["Batman", "Superman", "Spider-Man"],
        timeLimit: 10,
      },
      {
        question: "What is the name of the dinosaur park in Jurassic Park?",
        correctAnswer: "Isla Nublar",
        otherGuesses: ["Isla Sorna", "Isla Muerta", "Isla del Sol"],
        timeLimit: 20,
      },
      {
        question:
          "Which movie won the first Academy Award for Best Animated Feature?",
        correctAnswer: "Shrek",
        otherGuesses: ["Toy Story", "Finding Nemo", "Spirited Away"],
        timeLimit: 20,
      },
      {
        question: "Who composed the music for Star Wars?",
        correctAnswer: "John Williams",
        otherGuesses: ["Hans Zimmer", "Ennio Morricone", "James Horner"],
        timeLimit: 15,
      },
      {
        question: "Which movie features the character Ellen Ripley?",
        correctAnswer: "Alien",
        otherGuesses: ["Terminator", "Predator", "Blade Runner"],
        timeLimit: 15,
      },
      {
        question: "What is the highest-grossing R-rated movie?",
        correctAnswer: "Joker",
        otherGuesses: ["Deadpool", "The Matrix", "American Sniper"],
        timeLimit: 20,
      },
    ],
  },
  {
    name: "Music",
    description: "How well do you know music?",
    icon: "\ud83c\udfb5",
    questions: [
      {
        question: "Who is known as the King of Pop?",
        correctAnswer: "Michael Jackson",
        otherGuesses: ["Elvis Presley", "Prince", "Justin Timberlake"],
        timeLimit: 15,
      },
      {
        question: "What instrument does a pianist play?",
        correctAnswer: "Piano",
        otherGuesses: ["Guitar", "Violin", "Drums"],
        timeLimit: 10,
      },
      {
        question: "Which band wrote 'Bohemian Rhapsody'?",
        correctAnswer: "Queen",
        otherGuesses: ["The Beatles", "Led Zeppelin", "Pink Floyd"],
        timeLimit: 15,
      },
      {
        question: "What is the best-selling album of all time?",
        correctAnswer: "Thriller by Michael Jackson",
        otherGuesses: [
          "Back in Black by AC/DC",
          "The Dark Side of the Moon by Pink Floyd",
          "Rumours by Fleetwood Mac",
        ],
        timeLimit: 20,
      },
      {
        question: "Who sang 'Like a Virgin'?",
        correctAnswer: "Madonna",
        otherGuesses: ["Cyndi Lauper", "Cher", "Whitney Houston"],
        timeLimit: 15,
      },
      {
        question: "Which instrument is John Coltrane famous for playing?",
        correctAnswer: "Saxophone",
        otherGuesses: ["Trumpet", "Piano", "Drums"],
        timeLimit: 15,
      },
      {
        question: "What genre of music is Bob Marley associated with?",
        correctAnswer: "Reggae",
        otherGuesses: ["Rock", "Jazz", "Hip Hop"],
        timeLimit: 10,
      },
      {
        question: "Who composed 'The Four Seasons'?",
        correctAnswer: "Antonio Vivaldi",
        otherGuesses: [
          "Johann Sebastian Bach",
          "Wolfgang Amadeus Mozart",
          "Ludwig van Beethoven",
        ],
        timeLimit: 20,
      },
      {
        question: "Which city is considered the birthplace of jazz?",
        correctAnswer: "New Orleans",
        otherGuesses: ["Chicago", "New York", "Los Angeles"],
        timeLimit: 15,
      },
      {
        question: "What was Elvis Presley's first hit single?",
        correctAnswer: "Heartbreak Hotel",
        otherGuesses: ["Jailhouse Rock", "Hound Dog", "Blue Suede Shoes"],
        timeLimit: 20,
      },
      {
        question: "Which Beatle was known as the 'quiet one'?",
        correctAnswer: "George Harrison",
        otherGuesses: ["John Lennon", "Paul McCartney", "Ringo Starr"],
        timeLimit: 20,
      },
      {
        question: "What is the name of Taylor Swift's first album?",
        correctAnswer: "Taylor Swift",
        otherGuesses: ["Fearless", "Speak Now", "Debut"],
        timeLimit: 20,
      },
      {
        question: "Which artist has won the most Grammy Awards?",
        correctAnswer: "Georg Solti",
        otherGuesses: ["Beyoncé", "Quincy Jones", "Stevie Wonder"],
        timeLimit: 20,
      },
      {
        question: "What is the highest female singing voice?",
        correctAnswer: "Soprano",
        otherGuesses: ["Alto", "Mezzo-soprano", "Contralto"],
        timeLimit: 15,
      },
      {
        question: "Which musical instrument has 88 keys?",
        correctAnswer: "Piano",
        otherGuesses: ["Organ", "Harpsichord", "Synthesizer"],
        timeLimit: 10,
      },
      {
        question: "Who wrote the opera 'The Magic Flute'?",
        correctAnswer: "Mozart",
        otherGuesses: ["Beethoven", "Verdi", "Puccini"],
        timeLimit: 20,
      },
      {
        question: "Which band was Freddie Mercury the lead singer of?",
        correctAnswer: "Queen",
        otherGuesses: ["The Rolling Stones", "Led Zeppelin", "Pink Floyd"],
        timeLimit: 15,
      },
      {
        question: "What is the national instrument of Japan?",
        correctAnswer: "Koto",
        otherGuesses: ["Shamisen", "Taiko", "Biwa"],
        timeLimit: 20,
      },
      {
        question: "Who is known as the 'Queen of Soul'?",
        correctAnswer: "Aretha Franklin",
        otherGuesses: ["Diana Ross", "Whitney Houston", "Tina Turner"],
        timeLimit: 15,
      },
      {
        question: "Which composer went deaf later in life?",
        correctAnswer: "Beethoven",
        otherGuesses: ["Mozart", "Bach", "Chopin"],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "Sports",
    description: "Challenge your sports knowledge",
    icon: "\ud83c\udfc5",
    questions: [
      {
        question: "How many players are on a soccer team?",
        correctAnswer: "11",
        otherGuesses: ["10", "12", "9"],
        timeLimit: 10,
      },
      {
        question: "What country hosted the 2016 Summer Olympics?",
        correctAnswer: "Brazil",
        otherGuesses: ["China", "USA", "UK"],
        timeLimit: 15,
      },
      {
        question: "In what sport is the term 'love' used?",
        correctAnswer: "Tennis",
        otherGuesses: ["Football", "Cricket", "Basketball"],
        timeLimit: 10,
      },
      {
        question: "Which country won the 2018 FIFA World Cup?",
        correctAnswer: "France",
        otherGuesses: ["Croatia", "Belgium", "England"],
        timeLimit: 15,
      },
      {
        question: "What is the national sport of Japan?",
        correctAnswer: "Sumo wrestling",
        otherGuesses: ["Judo", "Karate", "Baseball"],
        timeLimit: 15,
      },
      {
        question: "How many rings are on the Olympic flag?",
        correctAnswer: "5",
        otherGuesses: ["4", "6", "7"],
        timeLimit: 10,
      },
      {
        question: "Which boxer was known as 'The Greatest'?",
        correctAnswer: "Muhammad Ali",
        otherGuesses: ["Mike Tyson", "Floyd Mayweather", "Sugar Ray Leonard"],
        timeLimit: 15,
      },
      {
        question: "In basketball, how many points is a free throw worth?",
        correctAnswer: "1",
        otherGuesses: ["2", "3", "4"],
        timeLimit: 10,
      },
      {
        question: "Which country invented golf?",
        correctAnswer: "Scotland",
        otherGuesses: ["England", "USA", "Netherlands"],
        timeLimit: 15,
      },
      {
        question: "What is the maximum score in a single frame of bowling?",
        correctAnswer: "30",
        otherGuesses: ["20", "25", "10"],
        timeLimit: 15,
      },
      {
        question: "Which sport uses terms like 'birdie' and 'eagle'?",
        correctAnswer: "Golf",
        otherGuesses: ["Badminton", "Tennis", "Baseball"],
        timeLimit: 10,
      },
      {
        question: "How many players are on a baseball team?",
        correctAnswer: "9",
        otherGuesses: ["10", "11", "8"],
        timeLimit: 10,
      },
      {
        question: "Which country has won the most FIFA World Cups?",
        correctAnswer: "Brazil",
        otherGuesses: ["Germany", "Italy", "Argentina"],
        timeLimit: 15,
      },
      {
        question: "In which sport would you perform a 'slam dunk'?",
        correctAnswer: "Basketball",
        otherGuesses: ["Volleyball", "Tennis", "Handball"],
        timeLimit: 10,
      },
      {
        question: "What is the distance of a marathon?",
        correctAnswer: "26.2 miles",
        otherGuesses: ["13.1 miles", "20 miles", "30 miles"],
        timeLimit: 15,
      },
      {
        question: "Which country won the first ever World Cup in 1930?",
        correctAnswer: "Uruguay",
        otherGuesses: ["Argentina", "Brazil", "Italy"],
        timeLimit: 20,
      },
      {
        question: "What is the highest possible break in snooker?",
        correctAnswer: "147",
        otherGuesses: ["100", "127", "155"],
        timeLimit: 20,
      },
      {
        question: "Which sport uses a shuttlecock?",
        correctAnswer: "Badminton",
        otherGuesses: ["Tennis", "Squash", "Table tennis"],
        timeLimit: 10,
      },
      {
        question: "How many holes are in a standard round of golf?",
        correctAnswer: "18",
        otherGuesses: ["9", "27", "36"],
        timeLimit: 10,
      },
      {
        question: "Which country hosted the 2008 Summer Olympics?",
        correctAnswer: "China",
        otherGuesses: ["Greece", "Australia", "UK"],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "Literature",
    description: "Dive into books and authors",
    icon: "\ud83d\udcda",
    questions: [
      {
        question: "Who wrote 'Romeo and Juliet'?",
        correctAnswer: "William Shakespeare",
        otherGuesses: ["Charles Dickens", "Mark Twain", "Jane Austen"],
        timeLimit: 15,
      },
      {
        question: "What is the name of the wizarding school in Harry Potter?",
        correctAnswer: "Hogwarts",
        otherGuesses: ["Ilvermorny", "Beauxbatons", "Durmstrang"],
        timeLimit: 10,
      },
      {
        question: "Who wrote '1984'?",
        correctAnswer: "George Orwell",
        otherGuesses: ["Aldous Huxley", "Ray Bradbury", "H.G. Wells"],
        timeLimit: 15,
      },
      {
        question: "What is the longest novel ever written?",
        correctAnswer: "In Search of Lost Time by Marcel Proust",
        otherGuesses: [
          "War and Peace by Leo Tolstoy",
          "Les Misérables by Victor Hugo",
          "Ulysses by James Joyce",
        ],
        timeLimit: 20,
      },
      {
        question: "Which book features the character Atticus Finch?",
        correctAnswer: "To Kill a Mockingbird",
        otherGuesses: [
          "The Great Gatsby",
          "The Catcher in the Rye",
          "Of Mice and Men",
        ],
        timeLimit: 15,
      },
      {
        question: "Who wrote 'Pride and Prejudice'?",
        correctAnswer: "Jane Austen",
        otherGuesses: ["Charlotte Brontë", "Emily Brontë", "Virginia Woolf"],
        timeLimit: 15,
      },
      {
        question: "What is the best-selling book of all time?",
        correctAnswer: "The Bible",
        otherGuesses: [
          "Quotations from Chairman Mao",
          "Harry Potter series",
          "The Lord of the Rings",
        ],
        timeLimit: 15,
      },
      {
        question: "Which Shakespeare play features the character Iago?",
        correctAnswer: "Othello",
        otherGuesses: ["Macbeth", "Hamlet", "King Lear"],
        timeLimit: 20,
      },
      {
        question: "Who wrote 'The Great Gatsby'?",
        correctAnswer: "F. Scott Fitzgerald",
        otherGuesses: [
          "Ernest Hemingway",
          "John Steinbeck",
          "William Faulkner",
        ],
        timeLimit: 15,
      },
      {
        question: "Which book begins with 'Call me Ishmael'?",
        correctAnswer: "Moby-Dick",
        otherGuesses: [
          "The Old Man and the Sea",
          "Treasure Island",
          "20,000 Leagues Under the Sea",
        ],
        timeLimit: 20,
      },
      {
        question: "Who created the character Sherlock Holmes?",
        correctAnswer: "Arthur Conan Doyle",
        otherGuesses: [
          "Agatha Christie",
          "Edgar Allan Poe",
          "Raymond Chandler",
        ],
        timeLimit: 15,
      },
      {
        question: "Which dystopian novel features 'Big Brother'?",
        correctAnswer: "1984",
        otherGuesses: [
          "Brave New World",
          "Fahrenheit 451",
          "The Handmaid's Tale",
        ],
        timeLimit: 15,
      },
      {
        question: "Who wrote 'The Odyssey'?",
        correctAnswer: "Homer",
        otherGuesses: ["Virgil", "Sophocles", "Plato"],
        timeLimit: 15,
      },
      {
        question: "Which book features a giant peach?",
        correctAnswer: "James and the Giant Peach",
        otherGuesses: [
          "Charlie and the Chocolate Factory",
          "The BFG",
          "Matilda",
        ],
        timeLimit: 10,
      },
      {
        question: "Who wrote 'The Catcher in the Rye'?",
        correctAnswer: "J.D. Salinger",
        otherGuesses: ["Jack Kerouac", "Kurt Vonnegut", "Hunter S. Thompson"],
        timeLimit: 15,
      },
      {
        question:
          "Which Shakespeare play features the line 'To be or not to be'?",
        correctAnswer: "Hamlet",
        otherGuesses: ["Macbeth", "Romeo and Juliet", "King Lear"],
        timeLimit: 15,
      },
      {
        question: "Who wrote 'The Lord of the Rings'?",
        correctAnswer: "J.R.R. Tolkien",
        otherGuesses: ["C.S. Lewis", "George R.R. Martin", "J.K. Rowling"],
        timeLimit: 15,
      },
      {
        question: "Which novel is set on the fictional planet Arrakis?",
        correctAnswer: "Dune",
        otherGuesses: [
          "Foundation",
          "Ender's Game",
          "The Left Hand of Darkness",
        ],
        timeLimit: 20,
      },
      {
        question: "Who wrote 'War and Peace'?",
        correctAnswer: "Leo Tolstoy",
        otherGuesses: ["Fyodor Dostoevsky", "Anton Chekhov", "Nikolai Gogol"],
        timeLimit: 15,
      },
      {
        question: "Which book features the character Huckleberry Finn?",
        correctAnswer: "Adventures of Huckleberry Finn",
        otherGuesses: [
          "Tom Sawyer",
          "Little Women",
          "The Adventures of Tom Bombadil",
        ],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "Technology",
    description: "Test your tech-savviness",
    icon: "\ud83d\udcbb",
    questions: [
      {
        question: "What does 'HTML' stand for?",
        correctAnswer: "HyperText Markup Language",
        otherGuesses: [
          "HighText Machine Language",
          "HyperText Machine Language",
          "HighText Marking Language",
        ],
        timeLimit: 15,
      },
      {
        question: "Who founded Microsoft?",
        correctAnswer: "Bill Gates",
        otherGuesses: ["Steve Jobs", "Mark Zuckerberg", "Elon Musk"],
        timeLimit: 10,
      },
      {
        question: "What year was the first iPhone released?",
        correctAnswer: "2007",
        otherGuesses: ["2005", "2008", "2006"],
        timeLimit: 15,
      },
      {
        question: "What does 'CPU' stand for?",
        correctAnswer: "Central Processing Unit",
        otherGuesses: [
          "Computer Processing Unit",
          "Central Power Unit",
          "Computer Power Unit",
        ],
        timeLimit: 15,
      },
      {
        question: "Which company created the Android operating system?",
        correctAnswer: "Google",
        otherGuesses: ["Microsoft", "Apple", "Samsung"],
        timeLimit: 15,
      },
      {
        question: "What does 'URL' stand for?",
        correctAnswer: "Uniform Resource Locator",
        otherGuesses: [
          "Universal Reference Link",
          "Uniform Reference Locator",
          "Universal Resource Locator",
        ],
        timeLimit: 20,
      },
      {
        question: "What was the first programmable computer?",
        correctAnswer: "ENIAC",
        otherGuesses: ["UNIVAC", "Colossus", "IBM 701"],
        timeLimit: 20,
      },
      {
        question: "Which social media platform has a blue bird logo?",
        correctAnswer: "Twitter",
        otherGuesses: ["Facebook", "Instagram", "LinkedIn"],
        timeLimit: 10,
      },
      {
        question: "What does 'Wi-Fi' stand for?",
        correctAnswer: "Wireless Fidelity",
        otherGuesses: [
          "Wireless Frequency",
          "Wireless Internet",
          "Wireless Function",
        ],
        timeLimit: 15,
      },
      {
        question: "What does 'Wi-Fi' stand for?",
        correctAnswer: "Wireless Fidelity",
        otherGuesses: [
          "Wireless Frequency",
          "Wireless Internet",
          "Wireless Function",
        ],
        timeLimit: 15,
      },
      {
        question: "Which programming language was created by Guido van Rossum?",
        correctAnswer: "Python",
        otherGuesses: ["Java", "C++", "JavaScript"],
        timeLimit: 15,
      },
      {
        question: "What was the first web browser called?",
        correctAnswer: "WorldWideWeb",
        otherGuesses: ["Mosaic", "Netscape", "Internet Explorer"],
        timeLimit: 20,
      },
      {
        question:
          "Which company developed the first commercial graphical user interface?",
        correctAnswer: "Xerox",
        otherGuesses: ["Apple", "Microsoft", "IBM"],
        timeLimit: 20,
      },
      {
        question: "What does 'RAM' stand for?",
        correctAnswer: "Random Access Memory",
        otherGuesses: [
          "Read Access Memory",
          "Random Available Memory",
          "Readily Accessible Memory",
        ],
        timeLimit: 15,
      },
      {
        question: "Which year was TikTok launched internationally?",
        correctAnswer: "2017",
        otherGuesses: ["2015", "2018", "2019"],
        timeLimit: 15,
      },
      {
        question: "What is the name of Amazon's virtual assistant?",
        correctAnswer: "Alexa",
        otherGuesses: ["Siri", "Cortana", "Google Assistant"],
        timeLimit: 10,
      },
      {
        question: "Which protocol is used to send email?",
        correctAnswer: "SMTP",
        otherGuesses: ["HTTP", "FTP", "TCP"],
        timeLimit: 20,
      },
      {
        question: "What was the first video uploaded to YouTube?",
        correctAnswer: "Me at the zoo",
        otherGuesses: [
          "Charlie bit my finger",
          "Evolution of Dance",
          "Baby Shark",
        ],
        timeLimit: 20,
      },
      {
        question: "Which company created the first computer mouse?",
        correctAnswer: "Xerox",
        otherGuesses: ["Apple", "Microsoft", "IBM"],
        timeLimit: 20,
      },
    ],
  },
  {
    name: "Food & Drink",
    description: "Test your culinary knowledge",
    icon: "\ud83c\udf74",
    questions: [
      {
        question: "What is the main ingredient in hummus?",
        correctAnswer: "Chickpeas",
        otherGuesses: ["Lentils", "Black beans", "Peas"],
        timeLimit: 15,
      },
      {
        question: "Which country produces the most coffee in the world?",
        correctAnswer: "Brazil",
        otherGuesses: ["Colombia", "Vietnam", "Indonesia"],
        timeLimit: 15,
      },
      {
        question:
          "What is the primary grain used in traditional Japanese sake?",
        correctAnswer: "Rice",
        otherGuesses: ["Wheat", "Barley", "Corn"],
        timeLimit: 15,
      },
      {
        question:
          "Which fruit is known as the 'king of fruits' in Southeast Asia?",
        correctAnswer: "Durian",
        otherGuesses: ["Mango", "Jackfruit", "Mangosteen"],
        timeLimit: 15,
      },
      {
        question: "What is the main ingredient in traditional tzatziki sauce?",
        correctAnswer: "Yogurt",
        otherGuesses: ["Mayonnaise", "Sour cream", "Cream cheese"],
        timeLimit: 15,
      },
      {
        question: "Which country invented pizza?",
        correctAnswer: "Italy",
        otherGuesses: ["USA", "Greece", "France"],
        timeLimit: 10,
      },
      {
        question: "What is the world's most expensive spice by weight?",
        correctAnswer: "Saffron",
        otherGuesses: ["Vanilla", "Cardamom", "Truffle"],
        timeLimit: 15,
      },
      {
        question: "Which alcoholic drink is made from juniper berries?",
        correctAnswer: "Gin",
        otherGuesses: ["Vodka", "Tequila", "Rum"],
        timeLimit: 15,
      },
      {
        question: "What is the national dish of Spain?",
        correctAnswer: "Paella",
        otherGuesses: ["Tapas", "Gazpacho", "Tortilla Española"],
        timeLimit: 15,
      },
      {
        question: "Which vegetable is the most consumed in the world?",
        correctAnswer: "Tomato",
        otherGuesses: ["Potato", "Onion", "Carrot"],
        timeLimit: 15,
      },
      {
        question: "What is the main ingredient in miso soup?",
        correctAnswer: "Fermented soybeans",
        otherGuesses: ["Seaweed", "Fish broth", "Mushrooms"],
        timeLimit: 20,
      },
      {
        question: "Which country consumes the most chocolate per capita?",
        correctAnswer: "Switzerland",
        otherGuesses: ["Belgium", "Germany", "USA"],
        timeLimit: 15,
      },
      {
        question: "What is the most expensive coffee in the world?",
        correctAnswer: "Kopi Luwak",
        otherGuesses: ["Blue Mountain", "Geisha", "Black Ivory"],
        timeLimit: 15,
      },
      {
        question: "Which fruit is used to make traditional mojitos?",
        correctAnswer: "Lime",
        otherGuesses: ["Lemon", "Orange", "Grapefruit"],
        timeLimit: 10,
      },
      {
        question: "What is the national dish of Thailand?",
        correctAnswer: "Pad Thai",
        otherGuesses: ["Green Curry", "Tom Yum", "Massaman Curry"],
        timeLimit: 15,
      },
      {
        question: "Which country invented champagne?",
        correctAnswer: "France",
        otherGuesses: ["Italy", "Spain", "Germany"],
        timeLimit: 10,
      },
      {
        question: "What is the most consumed meat in the world?",
        correctAnswer: "Pork",
        otherGuesses: ["Chicken", "Beef", "Lamb"],
        timeLimit: 15,
      },
      {
        question: "Which nut is used to make marzipan?",
        correctAnswer: "Almond",
        otherGuesses: ["Hazelnut", "Cashew", "Walnut"],
        timeLimit: 15,
      },
      {
        question: "What is the main ingredient in traditional borscht?",
        correctAnswer: "Beetroot",
        otherGuesses: ["Tomato", "Cabbage", "Potato"],
        timeLimit: 15,
      },
      {
        question: "Which country consumes the most ice cream per capita?",
        correctAnswer: "USA",
        otherGuesses: ["Australia", "New Zealand", "Canada"],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "Animals",
    description: "Test your knowledge of the animal kingdom",
    icon: "\ud83d\udc3b",
    questions: [
      {
        question: "What is the fastest land animal?",
        correctAnswer: "Cheetah",
        otherGuesses: ["Pronghorn antelope", "Lion", "Greyhound"],
        timeLimit: 10,
      },
      {
        question: "Which mammal has the longest gestation period?",
        correctAnswer: "Elephant",
        otherGuesses: ["Whale", "Giraffe", "Rhinoceros"],
        timeLimit: 15,
      },
      {
        question: "What is the only mammal capable of true flight?",
        correctAnswer: "Bat",
        otherGuesses: ["Flying squirrel", "Sugar glider", "Colugo"],
        timeLimit: 15,
      },
      {
        question: "Which animal has the strongest bite force?",
        correctAnswer: "Saltwater crocodile",
        otherGuesses: ["Hippopotamus", "Great white shark", "Gorilla"],
        timeLimit: 15,
      },
      {
        question: "What is the largest species of bear?",
        correctAnswer: "Polar bear",
        otherGuesses: ["Grizzly bear", "Kodiak bear", "Black bear"],
        timeLimit: 15,
      },
      {
        question: "Which bird has the largest wingspan?",
        correctAnswer: "Wandering albatross",
        otherGuesses: [
          "Andean condor",
          "Dalmatian pelican",
          "Great white pelican",
        ],
        timeLimit: 15,
      },
      {
        question: "What is the only continent without native bees?",
        correctAnswer: "Antarctica",
        otherGuesses: ["Australia", "South America", "Africa"],
        timeLimit: 15,
      },
      {
        question: "Which animal has three hearts?",
        correctAnswer: "Octopus",
        otherGuesses: ["Squid", "Cuttlefish", "Nautilus"],
        timeLimit: 15,
      },
      {
        question: "What is the world's largest living reptile?",
        correctAnswer: "Saltwater crocodile",
        otherGuesses: ["Nile crocodile", "Komodo dragon", "Green anaconda"],
        timeLimit: 15,
      },
      {
        question: "Which mammal lays eggs?",
        correctAnswer: "Platypus",
        otherGuesses: ["Echidna", "Marsupial mole", "None of these"],
        timeLimit: 15,
      },
      {
        question: "What is the tallest living animal?",
        correctAnswer: "Giraffe",
        otherGuesses: ["African elephant", "Ostrich", "Polar bear"],
        timeLimit: 10,
      },
      {
        question: "Which animal can live the longest?",
        correctAnswer: "Greenland shark",
        otherGuesses: ["Giant tortoise", "Bowhead whale", "Ocean quahog"],
        timeLimit: 15,
      },
      {
        question: "What is the most venomous fish?",
        correctAnswer: "Stonefish",
        otherGuesses: ["Lionfish", "Pufferfish", "Box jellyfish"],
        timeLimit: 15,
      },
      {
        question: "Which bird is the fastest in level flight?",
        correctAnswer: "Peregrine falcon",
        otherGuesses: [
          "Golden eagle",
          "Gyrfalcon",
          "White-throated needletail",
        ],
        timeLimit: 15,
      },
      {
        question: "What is the largest species of penguin?",
        correctAnswer: "Emperor penguin",
        otherGuesses: ["King penguin", "Gentoo penguin", "Adélie penguin"],
        timeLimit: 15,
      },
      {
        question: "Which animal has the most powerful kick?",
        correctAnswer: "Zebra",
        otherGuesses: ["Horse", "Kangaroo", "Ostrich"],
        timeLimit: 15,
      },
      {
        question: "What is the smallest species of primate?",
        correctAnswer: "Pygmy mouse lemur",
        otherGuesses: ["Tarsier", "Marmoset", "Bushbaby"],
        timeLimit: 20,
      },
      {
        question: "Which insect is the strongest relative to its size?",
        correctAnswer: "Dung beetle",
        otherGuesses: ["Ant", "Rhinoceros beetle", "Hercules beetle"],
        timeLimit: 15,
      },
      {
        question: "What is the loudest animal on Earth?",
        correctAnswer: "Sperm whale",
        otherGuesses: ["Howler monkey", "Lion", "Elephant"],
        timeLimit: 15,
      },
      {
        question: "Which animal has fingerprints most similar to humans?",
        correctAnswer: "Koala",
        otherGuesses: ["Chimpanzee", "Gorilla", "Orangutan"],
        timeLimit: 15,
      },
    ],
  },
  {
    name: "Art",
    description: "Test your knowledge of art history and famous works",
    icon: "\ud83c\udfa8",
    questions: [
      {
        question: "Who painted 'The Starry Night'?",
        correctAnswer: "Vincent van Gogh",
        otherGuesses: ["Pablo Picasso", "Claude Monet", "Salvador Dalí"],
        timeLimit: 15,
      },
      {
        question: "Which art movement was Salvador Dalí associated with?",
        correctAnswer: "Surrealism",
        otherGuesses: ["Cubism", "Impressionism", "Expressionism"],
        timeLimit: 15,
      },
      {
        question: "What is the most visited museum in the world?",
        correctAnswer: "Louvre",
        otherGuesses: [
          "British Museum",
          "Metropolitan Museum of Art",
          "Vatican Museums",
        ],
        timeLimit: 15,
      },
      {
        question: "Who sculpted 'David'?",
        correctAnswer: "Michelangelo",
        otherGuesses: [
          "Donatello",
          "Leonardo da Vinci",
          "Gian Lorenzo Bernini",
        ],
        timeLimit: 15,
      },
      {
        question: "Which artist cut off part of his own ear?",
        correctAnswer: "Vincent van Gogh",
        otherGuesses: ["Pablo Picasso", "Paul Gauguin", "Edvard Munch"],
        timeLimit: 15,
      },
      {
        question: "What is the most expensive painting ever sold?",
        correctAnswer: "Salvator Mundi by Leonardo da Vinci",
        otherGuesses: [
          "Interchange by Willem de Kooning",
          "The Card Players by Paul Cézanne",
          "Nafea Faa Ipoipo by Paul Gauguin",
        ],
        timeLimit: 20,
      },
      {
        question: "Which art style is Jackson Pollock known for?",
        correctAnswer: "Abstract Expressionism",
        otherGuesses: ["Pop Art", "Cubism", "Fauvism"],
        timeLimit: 15,
      },
      {
        question:
          "Who designed the Vietnam Veterans Memorial in Washington, D.C.?",
        correctAnswer: "Maya Lin",
        otherGuesses: ["Frank Gehry", "I.M. Pei", "Richard Serra"],
        timeLimit: 20,
      },
      {
        question: "Which ancient wonder was a giant statue in Rhodes?",
        correctAnswer: "Colossus of Rhodes",
        otherGuesses: ["Statue of Zeus", "Great Pyramid", "Hanging Gardens"],
        timeLimit: 15,
      },
      {
        question: "Who painted the ceiling of the Sistine Chapel?",
        correctAnswer: "Michelangelo",
        otherGuesses: ["Raphael", "Leonardo da Vinci", "Donatello"],
        timeLimit: 15,
      },
      {
        question:
          "Which artist was known for his 'Campbell's Soup Cans' artwork?",
        correctAnswer: "Andy Warhol",
        otherGuesses: [
          "Roy Lichtenstein",
          "Jasper Johns",
          "Robert Rauschenberg",
        ],
        timeLimit: 15,
      },
      {
        question:
          "What is the name of the famous painting by Edvard Munch featuring a screaming figure?",
        correctAnswer: "The Scream",
        otherGuesses: ["The Shout", "The Cry", "The Yell"],
        timeLimit: 15,
      },
      {
        question: "Which ancient civilization built the Nazca Lines?",
        correctAnswer: "Nazca culture",
        otherGuesses: ["Inca", "Maya", "Aztec"],
        timeLimit: 20,
      },
      {
        question: "Who painted 'Girl with a Pearl Earring'?",
        correctAnswer: "Johannes Vermeer",
        otherGuesses: ["Rembrandt", "Peter Paul Rubens", "Frans Hals"],
        timeLimit: 15,
      },
      {
        question: "Which art movement was Claude Monet a leader of?",
        correctAnswer: "Impressionism",
        otherGuesses: ["Post-Impressionism", "Realism", "Romanticism"],
        timeLimit: 15,
      },
      {
        question:
          "What is the name of the famous marble statue of a nude male by Michelangelo?",
        correctAnswer: "David",
        otherGuesses: ["Apollo", "Hercules", "Perseus"],
        timeLimit: 15,
      },
      {
        question: "Who created the 'Mobiles' and 'Stabiles' sculptures?",
        correctAnswer: "Alexander Calder",
        otherGuesses: [
          "Henry Moore",
          "Constantin Brâncuși",
          "Louise Bourgeois",
        ],
        timeLimit: 20,
      },
      {
        question: "Which painting technique uses small dots of color?",
        correctAnswer: "Pointillism",
        otherGuesses: ["Impasto", "Sfumato", "Chiaroscuro"],
        timeLimit: 15,
      },
      {
        question: "Who designed the Guggenheim Museum in New York?",
        correctAnswer: "Frank Lloyd Wright",
        otherGuesses: ["Le Corbusier", "Mies van der Rohe", "I.M. Pei"],
        timeLimit: 20,
      },
      {
        question:
          "Which artist painted 'The Persistence of Memory' with melting clocks?",
        correctAnswer: "Salvador Dalí",
        otherGuesses: ["René Magritte", "Max Ernst", "Joan Miró"],
        timeLimit: 15,
      },
    ],
  },
];
